language: node_js

# Building native addons on node v3+ requires a recent compiler.
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

# libsmc obviously only works on osx.
os: osx

node_js:
  - "node"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"

notifications:
  email: false
