language: node_js

# libsmc obviously only works on osx.
os: osx

node_js:
  - "node"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.11"

before_script:
  - "npm run lint"

notifications:
  email: false
